services:
  db:
    image: postgres:14.13  # Utilise la même version que celle que tu as déjà
    container_name: postgres_jo_paris
    environment:
      POSTGRES_USER: mowgli
      POSTGRES_PASSWORD: EspritNwaar74!
      POSTGRES_DB: jo_paris
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
