services:
  db:
    image: postgres:14.13  # Utilise la même version que celle que tu as déjà
    container_name: postgres_test_db
    environment:
      POSTGRES_USER: mowgli
      POSTGRES_PASSWORD: EspritNwaar74!
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
